-- 코드를 작성해주세요
select II.ITEM_ID, II.ITEM_NAME, II.RARITY
from ITEM_INFO II
join ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
where IT.PARENT_ITEM_ID IN
(select ITEM_ID
from ITEM_INFO
where RARITY = 'RARE')
order by ITEM_ID DESC